pcall(require, "impatient")

require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.telescope"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.bufferline"
require "user.autocommands"
require "user.colorizer"
-- require "user.transparent"
-- require "user.indentline"
require "user.whichkey"
require "user.nvim-tree"
require "user.lualine"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
